version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fruitshop_app
    ports:
      - "8080:80"
    environment:
      - DB_DSN=mysql:host=db;dbname=eCommerce
      - DB_USERNAME=fruituser
      - DB_PASSWORD=fruitpass
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/runtime
      - /var/www/html/web/assets

  db:
    image: mysql:8.0
    container_name: fruitshop_db
    restart: always
    environment:
      - MYSQL_DATABASE=eCommerce
      - MYSQL_USER=fruituser
      - MYSQL_PASSWORD=fruitpass
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
