services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fruitshop_app
    ports:
      - "8080:80"
    environment:
      - YII_ENV=${YII_ENV:-prod}
      - YII_DEBUG=${YII_DEBUG:-0}
      - DB_DSN=${DB_DSN:-pgsql:host=dpg-d5begcjuibrs73ce8lag-a.virginia-postgres.render.com;port=5432;dbname=fruitshop_db;sslmode=require}
      - DB_USERNAME=${DB_USERNAME:-fruitadmin}
      - DB_PASSWORD=${DB_PASSWORD:-6otaPMavrBeSxd7NayEGdP47NEEeuCaJ}
      - COOKIE_VALIDATION_KEY=${COOKIE_VALIDATION_KEY:-R_sbCgfxTckDQ-p0hNpD4Kb4NYYMont5}
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/runtime
      - /var/www/html/assets

